version: '3.8'


services: 
  db:
    image: mysql:latest
    restart: always
    container_name: myphpapp-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE:   somedatabase
    volumes:
      - ./data:/var/lib/mysql
  dbclient:
    image: mysql:latest
    depends_on: 
      - db
    command: mysql -u root -p somepassword -h db
