version: '3.8'


services: 
  web:
    image: nginx:alpine
    volumes:
      - ./nginix.conf:/etc/nginx/nginx.conf
    ports: 
      - 4200:80
    networks: 
      - pvt_net1
      - pvt_net2
  app1:
    image: httpd:latest
    networks: 
      - pvt_net1
  app2:
    image: httpd:latest
    networks: 
      - pvt_net2
networks: 
  pvt_net1:
  pvt_net2:
