version: '3.8'

services: 
  phpapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: phpapp:latest
    ports: 
      - "8080:80"
    volumes: 
      - "./:/var/www/html"
    container_name: myphpapp-app

  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: GROOT
    container_name: myphpapp-db
